services:
  postgres:
    image: postgres:16
    platform: linux/amd64
    container_name: ride-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: uberpassword
      POSTGRES_DB: ride_matching
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: